update snibdtap.si_ousp_nombre_correcciones
set categoriacatscat='',
nombrecatscat='',
estatuscatscat='',
autoridadcatscat='',
categoriavalidocatscat='',
nombrevalidocatscat='',
estatusvalidocatscat='',
autoridadvalidocatscat='';

update snibdtap.si_ousp_nombre_correcciones n inner join catalogocentralizado._TransformaTablaNombre t on n.idnombrecat=t.IdCAT
set n.categoriacatscat=t.UltimaCategoriaTaxonomica,
n.nombrecatscat=t.TaxonConSubgenero,
n.estatuscatscat=t.EstatusTaxon,
n.autoridadcatscat=t.AutorTaxon
where n.comentarioscat like '%Validado completamente con CAT%';

update snibdtap.si_ousp_nombre_correcciones n inner join catalogocentralizado._TransformaTablaNombre t on n.idnombrecatvalido=t.IdCAT
set n.categoriavalidocatscat=t.UltimaCategoriaTaxonomica,
n.nombrevalidocatscat=t.TaxonConSubgenero,
n.estatusvalidocatscat=t.EstatusTaxon,
n.autoridadvalidocatscat=t.AutorTaxon
where n.comentarioscatvalido like '%Validado completamente con CAT%';


UPDATE snibdtap.si_ousp_nombre_correcciones n1
SET n1.categoriacatscat= IF(n1.epitetoinfraespecifico2cat <> '',n1.categoriainfraespecie2cat,
IF(n1.epitetoinfraespecificocat <> '',n1.categoriainfraespeciecat ,
IF(n1.epitetoespecificocat <> '','especie',
IF(n1.subgenerocat <> '','subgénero',
IF(n1.generocat <> '','género',
IF(n1.tribucat <> '','tribu',
IF(n1.subfamiliacat <> '','subfamilia',
IF(n1.familiacat <> '','familia',
IF(n1.subordencat <> '','suborden',
IF(n1.ordencat <> '','orden',
IF(n1.clasecat <> '','clase',
IF(n1.divisionphylumcat <> '','divisionphylum',
IF(n1.reinocat <> '','Reino',''))))))))))))),
n1.nombrecatscat = IF(n1.epitetoinfraespecifico2cat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),''),' ',n1.epitetoespecificocat,' ',n1.epitetoinfraespecificocat,' ',n1.epitetoinfraespecifico2cat),
IF(n1.epitetoinfraespecificocat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),''),' ',n1.epitetoespecificocat,' ',n1.epitetoinfraespecificocat),
IF(n1.epitetoespecificocat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),''),' ',n1.epitetoespecificocat),
IF(n1.subgenerocat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),'')),
IF(n1.generocat <> '',n1.generocat,
IF(n1.tribucat <> '',n1.tribucat,
IF(n1.subfamiliacat <> '',n1.subfamiliacat,
IF(n1.familiacat <> '',n1.familiacat,
IF(n1.subordencat <> '',n1.subordencat,
IF(n1.ordencat <> '',n1.ordencat,
IF(n1.clasecat <> '',n1.clasecat,
IF(n1.divisionphylumcat <> '',n1.divisionphylumcat,
IF(n1.reinocat <> '',n1.reinocat,''))))))))))))),
n1.estatuscatscat=IF(n1.epitetoinfraespecifico2cat <> '',n1.estatusinfraespecie2cat,
IF(n1.epitetoinfraespecificocat <> '',n1.estatusinfraespeciecat ,
IF(n1.epitetoespecificocat <> '',n1.estatusespeciecat,
IF(n1.subgenerocat <> '',n1.estatussubgenerocat,
IF(n1.generocat <> '',n1.estatusgenerocat,
IF(n1.tribucat <> '',n1.estatustribucat,
IF(n1.subfamiliacat <> '',n1.estatussubfamiliacat,
IF(n1.familiacat <> '',n1.estatusfamiliacat,'')))))))),
n1.autoridadcatscat=IF(n1.epitetoinfraespecifico2cat <> '',n1.autoranioinfraespecie2cat,
IF(n1.epitetoinfraespecificocat <> '',n1.autoranioinfraespeciecat ,
IF(n1.epitetoespecificocat <> '',n1.autoranioespeciecat,
IF(n1.subgenerocat <> '',n1.autoraniosubgenerocat,
IF(n1.generocat <> '',n1.autoraniogenerocat,'')))))
WHERE n1.comentarioscat LIKE '%completamente con otra fuente%';


UPDATE snibdtap.si_ousp_nombre_correcciones n1
SET n1.categoriavalidocatscat= IF(n1.epitetoinfraespecifico2catvalido <> '',n1.categoriainfraespecie2catvalido,
IF(n1.epitetoinfraespecificocatvalido <> '',n1.categoriainfraespeciecatvalido ,
IF(n1.epitetoespecificocatvalido <> '','especie',
IF(n1.subgenerocatvalido <> '','subgénero',
IF(n1.generocatvalido <> '','género',
IF(n1.tribucatvalido <> '','tribu',
IF(n1.subfamiliacatvalido <> '','subfamila',
IF(n1.familiacatvalido <> '','familia',
IF(n1.subordencatvalido <> '','suborden',
IF(n1.ordencatvalido <> '','orden',
IF(n1.clasecatvalido <> '','clase',
IF(n1.divisionphylumcatvalido <> '','divisionphylum',
IF(n1.reinocatvalido <> '','Reino',''))))))))))))),
n1.nombrevalidocatscat=IF(n1.epitetoinfraespecifico2catvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),''),' ',n1.epitetoespecificocatvalido,' ',n1.epitetoinfraespecificocatvalido,' ',n1.epitetoinfraespecifico2catvalido),
IF(n1.epitetoinfraespecificocatvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),''),' ',n1.epitetoespecificocatvalido,' ',n1.epitetoinfraespecificocatvalido),
IF(n1.epitetoespecificocatvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),''),' ',n1.epitetoespecificocatvalido),
IF(n1.subgenerocatvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),'')),
IF(n1.generocatvalido <> '',n1.generocatvalido,
IF(n1.tribucatvalido <> '',n1.tribucatvalido,
IF(n1.subfamiliacatvalido <> '',n1.subfamiliacatvalido,
IF(n1.familiacatvalido <> '',n1.familiacatvalido,
IF(n1.subordencatvalido <> '',n1.subordencatvalido,
IF(n1.ordencatvalido <> '',n1.ordencatvalido,
IF(n1.clasecatvalido <> '',n1.clasecatvalido,
IF(n1.divisionphylumcatvalido <> '',n1.divisionphylumcatvalido,
IF(n1.reinocatvalido <> '',reinocatvalido,''))))))))))))),
n1.estatusvalidocatscat=IF(n1.epitetoinfraespecifico2catvalido <> '',n1.estatusinfraespecie2catvalido,
IF(n1.epitetoinfraespecificocatvalido <> '',n1.estatusinfraespeciecatvalido ,
IF(n1.epitetoespecificocatvalido <> '',n1.estatusespeciecatvalido,
IF(n1.subgenerocatvalido <> '',n1.estatussubgenerocatvalido,
IF(n1.generocatvalido <> '',n1.estatusgenerocatvalido,
IF(n1.tribucatvalido <> '',n1.estatustribucatvalido,
IF(n1.subfamiliacatvalido <> '',n1.estatussubfamiliacatvalido,
IF(n1.familiacatvalido <> '',n1.estatusfamiliacatvalido,'')))))))),
n1.autoridadvalidocatscat=IF(n1.epitetoinfraespecifico2catvalido <> '',n1.autoranioinfraespecie2catvalido,
IF(n1.epitetoinfraespecificocatvalido <> '',n1.autoranioinfraespeciecatvalido ,
IF(n1.epitetoespecificocatvalido <> '',n1.autoranioespeciecatvalido,
IF(n1.subgenerocatvalido <> '',n1.autoraniosubgenerocatvalido,
IF(n1.generocatvalido <> '',n1.autoraniogenerocatvalido,'')))))
WHERE n1.comentarioscatvalido LIKE '%completamente con otra fuente%';

-- actualizar el espejo

update snibdtap.si_ousp_nombre_correcciones
SET
    reinocatvalido = '',
    sistemaclasificacionreinocatvalido = '',
    divisionphylumcatvalido = '',
    sistemaclasificaciondivisionphylumcatvalido = '',
    clasecatvalido = '',
    sistemaclasificacionclasecatvalido = '',
    ordencatvalido = '',
    sistemaclasificacionordencatvalido = '',
    subordencatvalido = '',
    sistemaclasificacionsubordencatvalido = '',
    familiacatvalido = '',
	estatusfamiliacatvalido = '',
    sistemaclasificacionfamiliacatvalido = '',
    subfamiliacatvalido = '',
    sistemaclasificacionsubfamiliacatvalido = '',
    estatussubfamiliacatvalido = '',
    tribucatvalido = '',
    sistemaclasificaciontribucatvalido = '',
    estatustribucatvalido = '',
    generocatvalido = '',
    sistemaclasificaciongenerocatvalido = '',
    autoraniogenerocatvalido = '',
    estatusgenerocatvalido = '',
    subgenerocatvalido = '',
    sistemaclasificacionsubgenerocatvalido = '',
    autoraniosubgenerocatvalido = '',
    estatussubgenerocatvalido = '',
    epitetoespecificocatvalido = '',
    catdiccespeciecatvalido = '',
    autoranioespeciecatvalido = '',
    estatusespeciecatvalido = '',
    categoriainfraespeciecatvalido = '',
    epitetoinfraespecificocatvalido = '',
    catdiccinfraespeciecatvalido = '',
    autoranioinfraespeciecatvalido = '',
    estatusinfraespeciecatvalido = '',
	categoriainfraespecie2catvalido='',
    epitetoinfraespecifico2catvalido='',
    autoranioinfraespecie2catvalido='',
    estatusinfraespecie2catvalido='',
    catdiccinfraespecie2catvalido='',
    idnombrecatvalido = '',
    cattaxcatvalido = '',
    catalogocatvalido = '',
    comentarioscatvalido = '',
    fuentecatvalido = '',
    homonimosfamiliacatvalido = '',
    homonimosgenerocatvalido = '',
    homonimosespeciecatvalido = '',
    homonimosinfraespeciecatvalido = '',
    categoriavalidocatscat = '',
    nombrevalidocatscat = '',
    estatusvalidocatscat = '',
    autoridadvalidocatscat = ''
WHERE (comentarioscat like "%completamente%" and estatuscatscat in ('válido', 'aceptado'))
or (comentarioscat like '%completamente con otra fuente%' and estatuscatscat = '');

update snibdtap.si_ousp_nombre_correcciones
SET
    reinocatvalido = reinocat,
    sistemaclasificacionreinocatvalido = sistemaclasificacionreinocat,
    divisionphylumcatvalido = divisionphylumcat,
    sistemaclasificaciondivisionphylumcatvalido = sistemaclasificaciondivisionphylumcat,
    clasecatvalido = clasecat,
    sistemaclasificacionclasecatvalido = sistemaclasificacionclasecat,
    ordencatvalido = ordencat,
    sistemaclasificacionordencatvalido = sistemaclasificacionordencat,
    subordencatvalido = subordencat,
    sistemaclasificacionsubordencatvalido = sistemaclasificacionsubordencat,
    familiacatvalido = familiacat,
	estatusfamiliacatvalido = estatusfamiliacat,
    sistemaclasificacionfamiliacatvalido = sistemaclasificacionfamiliacat,
    subfamiliacatvalido = subfamiliacat,
    sistemaclasificacionsubfamiliacatvalido = sistemaclasificacionsubfamiliacat,
    estatussubfamiliacatvalido = estatussubfamiliacat,
    tribucatvalido = tribucat,
    sistemaclasificaciontribucatvalido = sistemaclasificaciontribucat,
    estatustribucatvalido = estatustribucat,
    generocatvalido = generocat,
    sistemaclasificaciongenerocatvalido = sistemaclasificaciongenerocat,
    autoraniogenerocatvalido = autoraniogenerocat,
    estatusgenerocatvalido = estatusgenerocat,
    subgenerocatvalido = subgenerocat,
    sistemaclasificacionsubgenerocatvalido = sistemaclasificacionsubgenerocat,
    autoraniosubgenerocatvalido = autoraniosubgenerocat,
    estatussubgenerocatvalido = estatussubgenerocat,
    epitetoespecificocatvalido = epitetoespecificocat,
    catdiccespeciecatvalido = catdiccespeciecat,
    autoranioespeciecatvalido = autoranioespeciecat,
    estatusespeciecatvalido = estatusespeciecat,
    categoriainfraespeciecatvalido = categoriainfraespeciecat,
    epitetoinfraespecificocatvalido = epitetoinfraespecificocat,
    catdiccinfraespeciecatvalido = catdiccinfraespeciecat,
    autoranioinfraespeciecatvalido = autoranioinfraespeciecat,
    estatusinfraespeciecatvalido = estatusinfraespeciecat,
	categoriainfraespecie2catvalido=categoriainfraespecie2cat,
    epitetoinfraespecifico2catvalido=epitetoinfraespecifico2cat,
    autoranioinfraespecie2catvalido=autoranioinfraespecie2cat,
    estatusinfraespecie2catvalido=estatusinfraespecie2cat,
    catdiccinfraespecie2catvalido=catdiccinfraespecie2cat,
    idnombrecatvalido = idnombrecat,
    cattaxcatvalido = cattaxcat,
    catalogocatvalido = catalogocat,
    comentarioscatvalido = comentarioscat,
    fuentecatvalido = fuentecat,
    homonimosfamiliacatvalido = homonimosfamilia,
    homonimosgenerocatvalido = homonimosgenero,
    homonimosespeciecatvalido = homonimosespecie,
    homonimosinfraespeciecatvalido = homonimosinfraespecie,
    categoriavalidocatscat = categoriacatscat,
    nombrevalidocatscat = nombrecatscat,
    estatusvalidocatscat = estatuscatscat,
    autoridadvalidocatscat = autoridadcatscat
WHERE (comentarioscat like "%completamente%" and estatuscatscat in ('válido', 'aceptado'))
or (comentarioscat like '%completamente con otra fuente%' and estatuscatscat = '');