create table snibdtap.cortevalidacion20201005
select * from ValidacionesSCAT.cortevalidacion;
-- #ActualizacompletamenteCAT, actualizamos los cat
update snibdtap.`#Actualiza_CompletamenteCAT` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecat_corregido=t.idcat
set c.reinocat=t.Reino,
c.sistemaclasificacionreinocat=t.SistClasCatDiccReino,
c.divisionphylumcat=t.Divisionphylum,
c.sistemaclasificaciondivisionphylumcat=t.SistClasCatDiccDivisionphylum,
c.clasecat=t.Clase,
c.sistemaclasificacionclasecat=t.SistClasCatDiccClase,
c.ordencat=t.Orden,
c.sistemaclasificacionordencat=t.SistClasCatDiccOrden,
c.subordencat=t.Suborden,
c.sistemaclasificacionsubordencat=t.SistClasCatDiccSubOrden,
c.familiacat=t.Familia,
c.sistemaclasificacionfamiliacat=t.SistClasCatDiccFamilia,
c.estatusfamiliacat=t.EstatusFamilia,
c.subfamiliacat=t.Subfamilia,
c.sistemaclasificacionsubfamiliacat=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacat=t.EstatusSubfamilia,
c.tribucat=t.Tribu,
c.sistemaclasificaciontribucat=t.SistClasCatDicctribu,
c.estatustribucat=t.EstatusTribu,
c.generocat=t.Genero,
c.sistemaclasificaciongenerocat=SistClasCatDiccGenero,
c.autoraniogenerocat=t.AutoridadGenero,
c.estatusgenerocat=t.EstatusGenero,
c.subgenerocat=t.Subgenero,
c.sistemaclasificacionsubgenerocat=t.SistClasCatDiccSubgenero,
c.autoraniosubgenerocat=t.AutoridadSubgenero,
c.estatussubgenerocat=t.EstatusSubgenero,
c.epitetoespecificocat=t.Especie_epiteto,
c.catdiccespeciecat=t.SistClasCatDiccEspecie_epiteto,
c.autoranioespeciecat=t.AutoridadEspecie_epiteto,
c.estatusespeciecat=t.EstatusEspecie_epiteto,
c.categoriainfraespeciecat=t.CategInfra,
c.epitetoinfraespecificocat=t.NombreInfra,
c.catdiccinfraespeciecat=t.SistClasCatDiccNombreInfra,
c.autoranioinfraespeciecat=t.AutoridadCategInfra,
c.estatusinfraespeciecat=t.EstatusCategInfra,
c.categoriainfraespecie2cat=t.CategSubInfra,
c.epitetoinfraespecifico2cat=t.NombreSubInfra,
c.autoranioinfraespecie2cat=t.AutoridadCategSubInfra,
c.estatusinfraespecie2cat=t.EstatusCategSubInfra,
c.catdiccinfraespecie2cat=t.SistClasCatDiccNombreSubInfra,
c.idnombrecat=t.IdCAT,
c.comentarioscat=a.comentarioscat_corregido,
c.fuentecat=t.Fuente,
c.catalogocat=t.Fuente,
c.cattaxcat=t.UltimaCategoriaTaxonomica,
c.gruposcat=t.GrupoSCAT;

-- #ActualizacompletamenteCAT, actualizamos los catvalidos
update snibdtap.`#Actualiza_CompletamenteCAT` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.reinocatvalido=t.Reino,
c.sistemaclasificacionreinocatvalido=t.SistClasCatDiccReino,
c.divisionphylumcatvalido=t.Divisionphylum,
c.sistemaclasificaciondivisionphylumcatvalido=t.SistClasCatDiccDivisionphylum,
c.clasecatvalido=t.Clase,
c.sistemaclasificacionclasecatvalido=t.SistClasCatDiccClase,
c.ordencatvalido=t.Orden,
c.sistemaclasificacionordencatvalido=t.SistClasCatDiccOrden,
c.subordencatvalido=t.Suborden,
c.sistemaclasificacionsubordencatvalido=t.SistClasCatDiccSubOrden,
c.familiacatvalido=t.Familia,
c.sistemaclasificacionfamiliacatvalido=t.SistClasCatDiccFamilia,
c.estatusfamiliacatvalido=t.EstatusFamilia,
c.subfamiliacatvalido=t.Subfamilia,
c.sistemaclasificacionsubfamiliacatvalido=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacatvalido=t.EstatusSubfamilia,
c.tribucatvalido=t.Tribu,
c.sistemaclasificaciontribucatvalido=t.SistClasCatDicctribu,
c.estatustribucatvalido=t.EstatusTribu,
c.generocatvalido=t.Genero,
c.sistemaclasificaciongenerocatvalido=SistClasCatDiccGenero,
c.autoraniogenerocatvalido=t.AutoridadGenero,
c.estatusgenerocatvalido=t.EstatusGenero,
c.subgenerocatvalido=t.Subgenero,
c.sistemaclasificacionsubgenerocatvalido=t.SistClasCatDiccSubgenero,
c.autoraniosubgenerocatvalido=t.AutoridadSubgenero,
c.estatussubgenerocatvalido=t.EstatusSubgenero,
c.epitetoespecificocatvalido=t.Especie_epiteto,
c.catdiccespeciecatvalido=t.SistClasCatDiccEspecie_epiteto,
c.autoranioespeciecatvalido=t.AutoridadEspecie_epiteto,
c.estatusespeciecatvalido=t.EstatusEspecie_epiteto,
c.categoriainfraespeciecatvalido=t.CategInfra,
c.epitetoinfraespecificocatvalido=t.NombreInfra,
c.catdiccinfraespeciecatvalido=t.SistClasCatDiccNombreInfra,
c.autoranioinfraespeciecatvalido=t.AutoridadCategInfra,
c.estatusinfraespeciecatvalido=t.EstatusCategInfra,
c.categoriainfraespecie2catvalido=t.CategSubInfra,
c.epitetoinfraespecifico2catvalido=t.NombreSubInfra,
c.autoranioinfraespecie2catvalido=t.AutoridadCategSubInfra,
c.estatusinfraespecie2catvalido=t.EstatusCategSubInfra,
c.catdiccinfraespecie2catvalido=t.SistClasCatDiccNombreSubInfra,
c.idnombrecatvalido=t.IdCAT,
c.comentarioscatvalido=a.comentarioscatvalido_corregido,
c.fuentecatvalido=t.Fuente,
c.catalogocatvalido=t.Fuente,
c.cattaxcatvalido=t.UltimaCategoriaTaxonomica;

-- 2.	#Actualiza_ idnombrecatvalido&comentarioscatvalido 
-- Tener cuidado con las categorías intermedias, cuando ultimacategoria esta por debajo de subfamilia, suborden o tribu se deja lo que traiga la TTN
update snibdtap.`#Actualiza_idnombrecatvalido&comentarioscatvalido` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.reinocatvalido=if(t.Reino='',c.reinocatvalido,t.Reino),
c.sistemaclasificacionreinocatvalido=if(t.SistClasCatDiccReino='',c.sistemaclasificacionReinocatvalido,t.SistClasCatDiccReino),
c.divisionphylumcatvalido=if(t.Divisionphylum='',c.divisionphylumcatvalido,t.Divisionphylum),
c.sistemaclasificaciondivisionphylumcatvalido=if(t.SistClasCatDiccDivisionphylum='',c.sistemaclasificaciondivisionphylumcatvalido,t.SistClasCatDiccDivisionphylum),
c.clasecatvalido=if(t.Clase='',c.clasecatvalido,t.Clase),
c.sistemaclasificacionclasecatvalido=if(t.SistClasCatDiccClase='',c.sistemaclasificacionclasecatvalido,t.SistClasCatDiccClase),
c.ordencatvalido=if(t.Orden='',c.ordencatvalido,t.Orden),
c.sistemaclasificacionordencatvalido=if(t.SistClasCatDiccOrden='',c.sistemaclasificacionordencatvalido,t.SistClasCatDiccOrden),
c.subordencatvalido=if(t.Suborden='',c.subordencatvalido,t.Suborden),
c.sistemaclasificacionsubordencatvalido=if(t.SistClasCatDiccSuborden='',c.sistemaclasificacionsubordencatvalido,t.SistClasCatDiccSuborden),
c.familiacatvalido=if(t.Familia='',c.familiacatvalido,t.Familia),
c.sistemaclasificacionfamiliacatvalido=if(t.SistClasCatDiccFamilia='',c.sistemaclasificacionfamiliacatvalido,t.SistClasCatDiccFamilia),
c.estatusfamiliacatvalido=if(t.EstatusFamilia='',c.estatusfamiliacatvalido,t.EstatusFamilia),
c.subfamiliacatvalido=if(t.Subfamilia='',c.subfamiliacatvalido,t.Subfamilia),
c.sistemaclasificacionsubfamiliacatvalido=if(t.SistClasCatDiccSubfamilia='',c.sistemaclasificacionsubfamiliacatvalido,t.SistClasCatDiccSubfamilia),
c.estatussubfamiliacatvalido=if(t.EstatusSubfamilia='',c.estatussubfamiliacatvalido,t.EstatusSubfamilia),
c.tribucatvalido=if(t.Tribu='',c.tribucatvalido,t.Tribu),
c.sistemaclasificaciontribucatvalido=if(t.SistClasCatDiccTribu='',c.sistemaclasificaciontribucatvalido,t.SistClasCatDiccTribu),
c.estatustribucatvalido=if(t.EstatusTribu='',c.estatustribucatvalido,t.EstatusTribu),
c.generocatvalido=if(t.Genero='',c.generocatvalido,t.Genero),
c.sistemaclasificaciongenerocatvalido=if(t.SistClasCatDiccGenero='',c.sistemaclasificaciongenerocatvalido,t.SistClasCatDiccGenero),
c.estatusgenerocatvalido=if(t.EstatusGenero='',c.estatusgenerocatvalido,t.EstatusGenero),
c.autoraniogenerocatvalido=if(t.AutoridadGenero='',c.autoraniogenerocatvalido,t.AutoridadGenero),
c.subgenerocatvalido=if(t.Subgenero='',c.subgenerocatvalido,t.Subgenero),
c.sistemaclasificacionsubgenerocatvalido=if(t.SistClasCatDiccSubgenero='',c.sistemaclasificacionsubgenerocatvalido,t.SistClasCatDiccSubgenero),
c.autoraniosubgenerocatvalido=if(t.AutoridadSubgenero='',c.autoraniosubgenerocatvalido,t.AutoridadSubgenero),
c.estatussubgenerocatvalido=if(t.EstatusSubgenero='',c.estatussubgenerocatvalido,t.EstatusSubgenero),
c.epitetoespecificocatvalido=if(t.Especie_epiteto='',c.epitetoespecificocatvalido,t.Especie_epiteto),
c.catdiccespeciecatvalido=if(t.SistClasCatDiccEspecie_epiteto='',c.catdiccespeciecatvalido,t.SistClasCatDiccEspecie_epiteto),
c.estatusespeciecatvalido=if(t.EstatusEspecie_epiteto='',c.estatusespeciecatvalido,t.EstatusEspecie_epiteto),
c.autoranioespeciecatvalido=if(t.AutoridadEspecie_epiteto='',c.autoranioespeciecatvalido,t.AutoridadEspecie_epiteto),
c.categoriainfraespeciecatvalido=if(t.CategInfra='',c.categoriainfraespeciecatvalido,t.CategInfra),
c.epitetoinfraespecificocatvalido=if(t.Nombreinfra='',c.epitetoinfraespecificocatvalido,t.Nombreinfra),
c.catdiccinfraespeciecatvalido=if(t.SistClasCatDiccNombreinfra='',c.catdiccinfraespeciecatvalido,t.SistClasCatDiccNombreinfra),
c.estatusinfraespeciecatvalido=if(t.EstatusCategInfra='',c.estatusinfraespeciecatvalido,t.EstatusCategInfra),
c.autoranioinfraespeciecatvalido=if(t.AutoridadCategInfra='',c.autoranioinfraespeciecatvalido,t.AutoridadCategInfra),
c.categoriainfraespecie2catvalido=if(t.CategSubinfra='',c.categoriainfraespecie2catvalido,t.CategSubinfra),
c.epitetoinfraespecifico2catvalido=if(t.NombreSubinfra='',c.epitetoinfraespecifico2catvalido,t.NombreSubinfra),
c.catdiccinfraespecie2catvalido=if(t.SistClasCatDiccNombreSubInfra='',c.catdiccinfraespecie2catvalido,t.SistClasCatDiccNombreSubInfra),
c.estatusinfraespecie2catvalido=if(t.EstatusCategSubInfra='',c.estatusinfraespecie2catvalido,t.EstatusCategSubInfra),
c.autoranioinfraespecie2catvalido=if(t.AutoridadCategSubInfra='',c.autoranioinfraespecie2catvalido,t.AutoridadCategSubInfra),
c.idnombrecatvalido=a.idnombrecatvalido_corregido,
c.cattaxcatvalido=t.UltimaCategoriaTaxonomica,
c.catalogocatvalido=t.Fuente,
c.comentarioscatvalido=a.comentarioscatvalido_corregido;

-- Con lo siguiente se corrige lo de las ctaegorías intermedias, revisar que no pase lo mismo en vinculo para los cat.

select t.ultimacategoriataxonomica,count(1)
from snibdtap.`#Actualiza_idnombrecatvalido&comentarioscatvalido` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat group by 1;

update snibdtap.`#Actualiza_idnombrecatvalido&comentarioscatvalido` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.subordencatvalido=t.Suborden,
c.sistemaclasificacionsubordencatvalido=t.SistClasCatDiccSuborden,
c.subfamiliacatvalido=t.Subfamilia,
c.sistemaclasificacionsubfamiliacatvalido=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacatvalido=t.EstatusSubfamilia,
c.tribucatvalido=t.Tribu,
c.sistemaclasificaciontribucatvalido=t.SistClasCatDiccTribu,
c.estatustribucatvalido=t.EstatusTribu
where t.ultimacategoriataxonomica in ('género');

update snibdtap.`#Actualiza_idnombrecatvalido&comentarioscatvalido` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.subordencatvalido=t.Suborden,
c.sistemaclasificacionsubordencatvalido=t.SistClasCatDiccSuborden,
c.subfamiliacatvalido=t.Subfamilia,
c.sistemaclasificacionsubfamiliacatvalido=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacatvalido=t.EstatusSubfamilia,
c.tribucatvalido=t.Tribu,
c.sistemaclasificaciontribucatvalido=t.SistClasCatDiccTribu,
c.estatustribucatvalido=t.EstatusTribu,
c.subgenerocatvalido=t.subgenero,
c.sistemaclasificacionsubgenerocatvalido=t.SistClasCatDiccSubgenero,
c.estatussubgenerocatvalido=t.EstatusSubgenero,
c.autoraniosubgenerocatvalido=t.autoridadsubgenero
where t.ultimacategoriataxonomica in ('especie');

update snibdtap.`#Actualiza_idnombrecatvalido&comentarioscatvalido` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.subordencatvalido=t.Suborden,
c.sistemaclasificacionsubordencatvalido=t.SistClasCatDiccSuborden
where t.ultimacategoriataxonomica in ('familia');

update snibdtap.`#Actualiza_CompletamenteCOL` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecat_corregido=t.idcat
set c.subordencat=t.Suborden,
c.sistemaclasificacionsubordencat=t.SistClasCatDiccSuborden,
c.subfamiliacat=t.Subfamilia,
c.sistemaclasificacionsubfamiliacat=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacat=t.EstatusSubfamilia,
c.tribucat=t.Tribu,
c.sistemaclasificaciontribucat=t.SistClasCatDiccTribu,
c.estatustribucat=t.EstatusTribu,
c.subgenerocat=t.subgenero,
c.sistemaclasificacionsubgenerocat=t.SistClasCatDiccSubgenero,
c.estatussubgenerocat=t.EstatusSubgenero,
c.autoraniosubgenerocat=t.autoridadsubgenero
where t.ultimacategoriataxonomica in ('especie');

-- 3.	#Actualiza_idnombrecat&comentarioscat_FaltaValidarTaxon
update snibdtap.`#Actualiza_idnombrecat&comentarioscat_FaltaValidarTaxon` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecat_corregido=t.idcat
set c.reinocat=t.Reino,
c.sistemaclasificacionreinocat=t.SistClasCatDiccReino,
c.divisionphylumcat=t.Divisionphylum,
c.sistemaclasificaciondivisionphylumcat=t.SistClasCatDiccDivisionphylum,
c.clasecat=t.Clase,
c.sistemaclasificacionclasecat=t.SistClasCatDiccClase,
c.ordencat=t.Orden,
c.sistemaclasificacionordencat=t.SistClasCatDiccOrden,
c.subordencat=t.Suborden,
c.sistemaclasificacionsubordencat=t.SistClasCatDiccSuborden,
c.familiacat=t.Familia,
c.sistemaclasificacionfamiliacat=t.SistClasCatDiccFamilia,
c.estatusfamiliacat=t.EstatusFamilia,
c.subfamiliacat=t.Subfamilia,
c.sistemaclasificacionsubfamiliacat=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacat=t.EstatusSubfamilia,
c.tribucat=t.Tribu,
c.sistemaclasificaciontribucat=t.SistClasCatDiccTribu,
c.estatustribucat=t.EstatusTribu,
c.generocat=t.Genero,
c.sistemaclasificaciongenerocat=t.SistClasCatDiccGenero,
c.estatusgenerocat=t.EstatusGenero,
c.autoraniogenerocat=t.AutoridadGenero,
c.subgenerocat=t.Subgenero,
c.sistemaclasificacionsubgenerocat=t.SistClasCatDiccSubgenero,
c.autoraniosubgenerocat=t.AutoridadSubgenero,
c.estatussubgenerocat=t.EstatusSubgenero,
c.epitetoespecificocat=t.Especie_epiteto,
c.catdiccespeciecat=t.SistClasCatDiccEspecie_epiteto,
c.estatusespeciecat=t.EstatusEspecie_epiteto,
c.autoranioespeciecat=t.AutoridadEspecie_epiteto,
c.categoriainfraespeciecat=t.CategInfra,
c.epitetoinfraespecificocat=t.Nombreinfra,
c.catdiccinfraespeciecat=t.SistClasCatDiccNombreinfra,
c.estatusinfraespeciecat=t.EstatusCategInfra,
c.autoranioinfraespeciecat=t.AutoridadCategInfra,
c.categoriainfraespecie2cat=t.CategSubinfra,
c.epitetoinfraespecifico2cat=t.NombreSubinfra,
c.catdiccinfraespecie2cat=t.SistClasCatDiccNombreSubInfra,
c.estatusinfraespecie2cat=t.EstatusCategSubInfra,
c.autoranioinfraespecie2cat=t.AutoridadCategSubInfra,
c.idnombrecat=a.idnombrecat_corregido,
c.cattaxcat=t.UltimaCategoriaTaxonomica,
c.catalogocat=t.Fuente,
c.comentarioscat=a.comentarioscat_corregido,
c.fuentecat='',
c.reinocatvalido='',
c.sistemaclasificacionReinocatvalido='',
c.divisionphylumcatvalido='',
c.sistemaclasificaciondivisionphylumcatvalido='',
c.clasecatvalido='',
c.sistemaclasificacionclasecatvalido='',
c.ordencatvalido='',
c.sistemaclasificacionordencatvalido='',
c.subordencatvalido='',
c.sistemaclasificacionsubordencatvalido='',
c.familiacatvalido='',
c.sistemaclasificacionfamiliacatvalido='',
c.estatusfamiliacatvalido='',
c.subfamiliacatvalido='',
c.sistemaclasificacionsubfamiliacatvalido='',
c.Estatussubfamiliacatvalido='',
c.tribucatvalido='',
c.sistemaclasificaciontribucatvalido='',
c.estatustribucatvalido='',
c.generocatvalido='',
c.sistemaclasificaciongenerocatvalido='',
c.estatusgenerocatvalido='',
c.autoraniogenerocatvalido='',
c.subgenerocatvalido='',
c.sistemaclasificacionsubgenerocatvalido='',
c.autoraniosubgenerocatvalido='',
c.estatussubgenerocatvalido='',
c.epitetoespecificocatvalido='',
c.catdiccespeciecatvalido='',
c.estatusespeciecatvalido='',
c.autoranioespeciecatvalido='',
c.categoriainfraespeciecatvalido='',
c.epitetoinfraespecificocatvalido='',
c.catdiccinfraespeciecatvalido='',
c.estatusinfraespeciecatvalido='',
c.autoranioinfraespeciecatvalido='',
c.categoriainfraespecie2catvalido='',
c.epitetoinfraespecifico2catvalido='',
c.catdiccinfraespecie2catvalido='',
c.estatusinfraespecie2catvalido='',
c.autoranioinfraespecie2catvalido='',
c.idnombrecatvalido='',
c.cattaxcatvalido='',
c.categoriavalidocatscat='',
c.nombrevalidocatscat='',
c.estatusvalidocatscat='',
c.autoridadvalidocatscat ='',
c.catalogocatvalido='',
c.comentarioscatvalido='',
c.fuentecatvalido='',
c.homonimosfamiliacatvalido='',
c.homonimosgenerocatvalido='',
c.homonimosespeciecatvalido='',
c.homonimosinfraespeciecatvalido='',
c.ambientenombre='',
c.origenambientenombre='',
c.prioritarias='',
c.nivelprioridad='',
c.estatusinvasora='';

-- 4.	#Actualiza_comentarioscat
update snibdtap.`#Actualiza_comentarioscat` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
set c.comentarioscat=a.comentarioscat_corregido;

-- 5.	#Actualiza_llaveagrupado_verificada
update snibdtap.`#Actualiza_llaveagrupado_verificada` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join ValidacionesSCAT.cortevalidacion c1 on a.llaveagrupado_verificada=c1.llaveagrupado
set 
c.reinocat=c1.reinocat,
c.sistemaclasificacionreinocat=c1.sistemaclasificacionreinocat,
c.divisionphylumcat=c1.divisionphylumcat,
c.sistemaclasificaciondivisionphylumcat=c1.sistemaclasificaciondivisionphylumcat,
c.clasecat=c1.clasecat,
c.sistemaclasificacionclasecat=c1.sistemaclasificacionclasecat,
c.ordencat=c1.ordencat,
c.sistemaclasificacionordencat=c1.sistemaclasificacionordencat,
c.subordencat=c1.subordencat,
c.sistemaclasificacionsubordencat=c1.sistemaclasificacionsubordencat,
c.familiacat=c1.familiacat,
c.sistemaclasificacionfamiliacat=c1.sistemaclasificacionfamiliacat,
c.estatusfamiliacat=c1.estatusfamiliacat,
c.subfamiliacat=c1.subfamiliacat,
c.sistemaclasificacionsubfamiliacat=c1.sistemaclasificacionsubfamiliacat,
c.estatussubfamiliacat=c1.estatussubfamiliacat,
c.tribucat=c1.tribucat,
c.sistemaclasificaciontribucat=c1.sistemaclasificaciontribucat,
c.estatustribucat=c1.estatustribucat,
c.generocat=c1.generocat,
c.sistemaclasificaciongenerocat=c1.sistemaclasificaciongenerocat,
c.autoraniogenerocat=c1.autoraniogenerocat,
c.estatusgenerocat=c1.estatusgenerocat,
c.subgenerocat=c1.subgenerocat,
c.sistemaclasificacionsubgenerocat=c1.sistemaclasificacionsubgenerocat,
c.autoraniosubgenerocat=c1.autoraniosubgenerocat,
c.estatussubgenerocat=c1.estatussubgenerocat,
c.epitetoespecificocat=c1.epitetoespecificocat,
c.catdiccespeciecat=c1.catdiccespeciecat,
c.autoranioespeciecat=c1.autoranioespeciecat,
c.estatusespeciecat=c1.estatusespeciecat,
c.categoriainfraespeciecat=c1.categoriainfraespeciecat,
c.epitetoinfraespecificocat=c1.epitetoinfraespecificocat,
c.catdiccinfraespeciecat=c1.catdiccinfraespeciecat,
c.autoranioinfraespeciecat=c1.autoranioinfraespeciecat,
c.estatusinfraespeciecat=c1.estatusinfraespeciecat,
c.categoriainfraespecie2cat=c1.categoriainfraespecie2cat,
c.epitetoinfraespecifico2cat=c1.epitetoinfraespecifico2cat,
c.autoranioinfraespecie2cat=c1.autoranioinfraespecie2cat,
c.estatusinfraespecie2cat=c1.estatusinfraespecie2cat,
c.catdiccinfraespecie2cat=c1.catdiccinfraespecie2cat,
c.idnombrecat=c1.idnombrecat,
c.comentarioscat=c1.comentarioscat,
c.fuentecat=c1.fuentecat,
c.catalogocat=c1.catalogocat,
c.cattaxcat=c1.cattaxcat,
c.reinocatvalido=c1.reinocatvalido,
c.sistemaclasificacionreinocatvalido=c1.sistemaclasificacionreinocatvalido,
c.divisionphylumcatvalido=c1.divisionphylumcatvalido,
c.sistemaclasificaciondivisionphylumcatvalido=c1.sistemaclasificaciondivisionphylumcatvalido,
c.clasecatvalido=c1.clasecatvalido,
c.sistemaclasificacionclasecatvalido=c1.sistemaclasificacionclasecatvalido,
c.ordencatvalido=c1.ordencatvalido,
c.sistemaclasificacionordencatvalido=c1.sistemaclasificacionordencatvalido,
c.subordencatvalido=c1.subordencatvalido,
c.sistemaclasificacionsubordencatvalido=c1.sistemaclasificacionsubordencatvalido,
c.familiacatvalido=c1.familiacatvalido,
c.sistemaclasificacionfamiliacatvalido=c1.sistemaclasificacionfamiliacatvalido,
c.estatusfamiliacatvalido=c1.estatusfamiliacatvalido,
c.subfamiliacatvalido=c1.subfamiliacatvalido,
c.sistemaclasificacionsubfamiliacatvalido=c1.sistemaclasificacionsubfamiliacatvalido,
c.estatussubfamiliacatvalido=c1.estatussubfamiliacatvalido,
c.tribucatvalido=c1.tribucatvalido,
c.sistemaclasificaciontribucatvalido=c1.sistemaclasificaciontribucatvalido,
c.estatustribucatvalido=c1.estatustribucatvalido,
c.generocatvalido=c1.generocatvalido,
c.sistemaclasificaciongenerocatvalido=c1.sistemaclasificaciongenerocatvalido,
c.autoraniogenerocatvalido=c1.autoraniogenerocatvalido,
c.estatusgenerocatvalido=c1.estatusgenerocatvalido,
c.subgenerocatvalido=c1.subgenerocatvalido,
c.sistemaclasificacionsubgenerocatvalido=c1.sistemaclasificacionsubgenerocatvalido,
c.autoraniosubgenerocatvalido=c1.autoraniosubgenerocatvalido,
c.estatussubgenerocatvalido=c1.estatussubgenerocatvalido,
c.epitetoespecificocatvalido=c1.epitetoespecificocatvalido,
c.catdiccespeciecatvalido=c1.catdiccespeciecatvalido,
c.autoranioespeciecatvalido=c1.autoranioespeciecatvalido,
c.estatusespeciecatvalido=c1.estatusespeciecatvalido,
c.categoriainfraespeciecatvalido=c1.categoriainfraespeciecatvalido,
c.epitetoinfraespecificocatvalido=c1.epitetoinfraespecificocatvalido,
c.catdiccinfraespeciecatvalido=c1.catdiccinfraespeciecatvalido,
c.autoranioinfraespeciecatvalido=c1.autoranioinfraespeciecatvalido,
c.estatusinfraespeciecatvalido=c1.estatusinfraespeciecatvalido,
c.categoriainfraespecie2catvalido=c1.categoriainfraespecie2catvalido,
c.epitetoinfraespecifico2catvalido=c1.epitetoinfraespecifico2catvalido,
c.autoranioinfraespecie2catvalido=c1.autoranioinfraespecie2catvalido,
c.estatusinfraespecie2catvalido=c1.estatusinfraespecie2catvalido,
c.catdiccinfraespecie2catvalido=c1.catdiccinfraespecie2catvalido,
c.idnombrecatvalido=c1.idnombrecatvalido,
c.comentarioscatvalido=c1.comentarioscatvalido,
c.fuentecatvalido=c1.fuentecatvalido,
c.catalogocatvalido=c1.catalogocatvalido,
c.cattaxcatvalido=c1.cattaxcatvalido,
c.gruposcat=c1.gruposcat;

-- 6.	Actualizar para todos los registros el campo grupo 
update catalogocentralizado.`Equivalencias_GrupoSCAT&Grupo` e inner join ValidacionesSCAT.cortevalidacion c on e.gruposcat=c.gruposcat
set c.grupo=e.Grupo;

-- 7. Llenar campos resumen cat y catvalidos, actualizar el espejo de acuerdo con lo indicado en el jira SNIB-2434.

-- actualizar los campos resumen

update ValidacionesSCAT.cortevalidacion c inner join snibdtap.llaveagrupado l on c.llaveagrupado=l.llaveagrupado
set categoriacatscat='',
nombrecatscat='',
estatuscatscat='',
autoridadcatscat='',
categoriavalidocatscat='',
nombrevalidocatscat='',
estatusvalidocatscat='',
autoridadvalidocatscat='';

update ValidacionesSCAT.cortevalidacion n inner join snibdtap.llaveagrupado l on n.llaveagrupado=l.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on n.idnombrecat=t.IdCAT
set n.categoriacatscat=t.UltimaCategoriaTaxonomica,
n.nombrecatscat=t.TaxonConSubgenero,
n.estatuscatscat=t.EstatusTaxon,
n.autoridadcatscat=t.AutorTaxon
where n.comentarioscat like '%Validado completamente con CAT%';

update ValidacionesSCAT.cortevalidacion n inner join snibdtap.llaveagrupado l on n.llaveagrupado=l.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on n.idnombrecatvalido=t.IdCAT
set n.categoriavalidocatscat=t.UltimaCategoriaTaxonomica,
n.nombrevalidocatscat=t.TaxonConSubgenero,
n.estatusvalidocatscat=t.EstatusTaxon,
n.autoridadvalidocatscat=t.AutorTaxon
where n.comentarioscatvalido like '%Validado completamente con CAT%';


UPDATE ValidacionesSCAT.cortevalidacion n1 inner join snibdtap.llaveagrupado l on n1.llaveagrupado=l.llaveagrupado
SET n1.categoriacatscat= IF(n1.epitetoinfraespecifico2cat <> '',n1.categoriainfraespecie2cat,
IF(n1.epitetoinfraespecificocat <> '',n1.categoriainfraespeciecat ,
IF(n1.epitetoespecificocat <> '','especie',
IF(n1.subgenerocat <> '','subgénero',
IF(n1.generocat <> '','género',
IF(n1.tribucat <> '','tribu',
IF(n1.subfamiliacat <> '','subfamila',
IF(n1.familiacat <> '','familia',
IF(n1.subordencat <> '','suborden',
IF(n1.ordencat <> '','orden',
IF(n1.clasecat <> '','clase',
IF(n1.divisionphylumcat <> '','divisionphylum',
IF(n1.reinocat <> '','Reino',''))))))))))))),
n1.nombrecatscat = IF(n1.epitetoinfraespecifico2cat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),''),' ',n1.epitetoespecificocat,' ',n1.epitetoinfraespecificocat,' ',n1.epitetoinfraespecifico2cat),
IF(n1.epitetoinfraespecificocat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),''),' ',n1.epitetoespecificocat,' ',n1.epitetoinfraespecificocat),
IF(n1.epitetoespecificocat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),''),' ',n1.epitetoespecificocat),
IF(n1.subgenerocat <> '',CONCAT(n1.generocat,IF(n1.subgenerocat <> '',CONCAT(' (',n1.subgenerocat,')'),'')),
IF(n1.generocat <> '',n1.generocat,
IF(n1.tribucat <> '',n1.tribucat,
IF(n1.subfamiliacat <> '',n1.subfamiliacat,
IF(n1.familiacat <> '',n1.familiacat,
IF(n1.subordencat <> '',n1.subordencat,
IF(n1.ordencat <> '',n1.ordencat,
IF(n1.clasecat <> '',n1.clasecat,
IF(n1.divisionphylumcat <> '',n1.divisionphylumcat,
IF(n1.reinocat <> '',n1.reinocat,''))))))))))))),
n1.estatuscatscat=IF(n1.epitetoinfraespecifico2cat <> '',n1.estatusinfraespecie2cat,
IF(n1.epitetoinfraespecificocat <> '',n1.estatusinfraespeciecat ,
IF(n1.epitetoespecificocat <> '',n1.estatusespeciecat,
IF(n1.subgenerocat <> '',n1.estatussubgenerocat,
IF(n1.generocat <> '',n1.estatusgenerocat,
IF(n1.tribucat <> '',n1.estatustribucat,
IF(n1.subfamiliacat <> '',n1.estatussubfamiliacat,
IF(n1.familiacat <> '',n1.estatusfamiliacat,'')))))))),
n1.autoridadcatscat=IF(n1.epitetoinfraespecifico2cat <> '',n1.autoranioinfraespecie2cat,
IF(n1.epitetoinfraespecificocat <> '',n1.autoranioinfraespeciecat ,
IF(n1.epitetoespecificocat <> '',n1.autoranioespeciecat,
IF(n1.subgenerocat <> '',n1.autoraniosubgenerocat,
IF(n1.generocat <> '',n1.autoraniogenerocat,'')))))
WHERE n1.comentarioscat LIKE '%completamente con otra fuente%';


UPDATE ValidacionesSCAT.cortevalidacion n1 inner join snibdtap.llaveagrupado l on n1.llaveagrupado=l.llaveagrupado
SET n1.categoriavalidocatscat= IF(n1.epitetoinfraespecifico2catvalido <> '',n1.categoriainfraespecie2catvalido,
IF(n1.epitetoinfraespecificocatvalido <> '',n1.categoriainfraespeciecatvalido ,
IF(n1.epitetoespecificocatvalido <> '','especie',
IF(n1.subgenerocatvalido <> '','subgénero',
IF(n1.generocatvalido <> '','género',
IF(n1.tribucatvalido <> '','tribu',
IF(n1.subfamiliacatvalido <> '','subfamila',
IF(n1.familiacatvalido <> '','familia',
IF(n1.subordencatvalido <> '','suborden',
IF(n1.ordencatvalido <> '','orden',
IF(n1.clasecatvalido <> '','clase',
IF(n1.divisionphylumcatvalido <> '','divisionphylum',
IF(n1.reinocatvalido <> '','Reino',''))))))))))))),
n1.nombrevalidocatscat=IF(n1.epitetoinfraespecifico2catvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),''),' ',n1.epitetoespecificocatvalido,' ',n1.epitetoinfraespecificocatvalido,' ',n1.epitetoinfraespecifico2catvalido),
IF(n1.epitetoinfraespecificocatvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),''),' ',n1.epitetoespecificocatvalido,' ',n1.epitetoinfraespecificocatvalido),
IF(n1.epitetoespecificocatvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),''),' ',n1.epitetoespecificocatvalido),
IF(n1.subgenerocatvalido <> '',CONCAT(n1.generocatvalido,IF(n1.subgenerocatvalido <> '',CONCAT(' (',n1.subgenerocatvalido,')'),'')),
IF(n1.generocatvalido <> '',n1.generocatvalido,
IF(n1.tribucatvalido <> '',n1.tribucatvalido,
IF(n1.subfamiliacatvalido <> '',n1.subfamiliacatvalido,
IF(n1.familiacatvalido <> '',n1.familiacatvalido,
IF(n1.subordencatvalido <> '',n1.subordencatvalido,
IF(n1.ordencatvalido <> '',n1.ordencatvalido,
IF(n1.clasecatvalido <> '',n1.clasecatvalido,
IF(n1.divisionphylumcatvalido <> '',n1.divisionphylumcatvalido,
IF(n1.reinocatvalido <> '',reinocatvalido,''))))))))))))),
n1.estatusvalidocatscat=IF(n1.epitetoinfraespecifico2catvalido <> '',n1.estatusinfraespecie2catvalido,
IF(n1.epitetoinfraespecificocatvalido <> '',n1.estatusinfraespeciecatvalido ,
IF(n1.epitetoespecificocatvalido <> '',n1.estatusespeciecatvalido,
IF(n1.subgenerocatvalido <> '',n1.estatussubgenerocatvalido,
IF(n1.generocatvalido <> '',n1.estatusgenerocatvalido,
IF(n1.tribucatvalido <> '',n1.estatustribucatvalido,
IF(n1.subfamiliacatvalido <> '',n1.estatussubfamiliacatvalido,
IF(n1.familiacatvalido <> '',n1.estatusfamiliacatvalido,'')))))))),
n1.autoridadvalidocatscat=IF(n1.epitetoinfraespecifico2catvalido <> '',n1.autoranioinfraespecie2catvalido,
IF(n1.epitetoinfraespecificocatvalido <> '',n1.autoranioinfraespeciecatvalido ,
IF(n1.epitetoespecificocatvalido <> '',n1.autoranioespeciecatvalido,
IF(n1.subgenerocatvalido <> '',n1.autoraniosubgenerocatvalido,
IF(n1.generocatvalido <> '',n1.autoraniogenerocatvalido,'')))))
WHERE n1.comentarioscatvalido LIKE '%completamente con otra fuente%';

-- actualizar el espejo

update ValidacionesSCAT.cortevalidacion c inner join snibdtap.llaveagrupado l on c.llaveagrupado=l.llaveagrupado
SET
    reinocatvalido = '',
    sistemaclasificacionreinocatvalido = '',
    divisionphylumcatvalido = '',
    sistemaclasificaciondivisionphylumcatvalido = '',
    clasecatvalido = '',
    sistemaclasificacionclasecatvalido = '',
    ordencatvalido = '',
    sistemaclasificacionordencatvalido = '',
    subordencatvalido = '',
    sistemaclasificacionsubordencatvalido = '',
    familiacatvalido = '',
	estatusfamiliacatvalido = '',
    sistemaclasificacionfamiliacatvalido = '',
    subfamiliacatvalido = '',
    sistemaclasificacionsubfamiliacatvalido = '',
    estatussubfamiliacatvalido = '',
    tribucatvalido = '',
    sistemaclasificaciontribucatvalido = '',
    estatustribucatvalido = '',
    generocatvalido = '',
    sistemaclasificaciongenerocatvalido = '',
    autoraniogenerocatvalido = '',
    estatusgenerocatvalido = '',
    subgenerocatvalido = '',
    sistemaclasificacionsubgenerocatvalido = '',
    autoraniosubgenerocatvalido = '',
    estatussubgenerocatvalido = '',
    epitetoespecificocatvalido = '',
    catdiccespeciecatvalido = '',
    autoranioespeciecatvalido = '',
    estatusespeciecatvalido = '',
    categoriainfraespeciecatvalido = '',
    epitetoinfraespecificocatvalido = '',
    catdiccinfraespeciecatvalido = '',
    autoranioinfraespeciecatvalido = '',
    estatusinfraespeciecatvalido = '',
	categoriainfraespecie2catvalido='',
    epitetoinfraespecifico2catvalido='',
    autoranioinfraespecie2catvalido='',
    estatusinfraespecie2catvalido='',
    catdiccinfraespecie2catvalido='',
    idnombrecatvalido = '',
    cattaxcatvalido = '',
    catalogocatvalido = '',
    comentarioscatvalido = '',
    fuentecatvalido = '',
    homonimosfamiliacatvalido = '',
    homonimosgenerocatvalido = '',
    homonimosespeciecatvalido = '',
    homonimosinfraespeciecatvalido = '',
    categoriavalidocatscat = '',
    nombrevalidocatscat = '',
    estatusvalidocatscat = '',
    autoridadvalidocatscat = ''
WHERE (comentarioscat like "%completamente%" and estatuscatscat in ('válido', 'aceptado'))
or (comentarioscat like '%completamente con otra fuente%' and estatuscatscat = '');

update ValidacionesSCAT.cortevalidacion c inner join snibdtap.llaveagrupado l on c.llaveagrupado=l.llaveagrupado
SET
    reinocatvalido = reinocat,
    sistemaclasificacionreinocatvalido = sistemaclasificacionreinocat,
    divisionphylumcatvalido = divisionphylumcat,
    sistemaclasificaciondivisionphylumcatvalido = sistemaclasificaciondivisionphylumcat,
    clasecatvalido = clasecat,
    sistemaclasificacionclasecatvalido = sistemaclasificacionclasecat,
    ordencatvalido = ordencat,
    sistemaclasificacionordencatvalido = sistemaclasificacionordencat,
    subordencatvalido = subordencat,
    sistemaclasificacionsubordencatvalido = sistemaclasificacionsubordencat,
    familiacatvalido = familiacat,
	estatusfamiliacatvalido = estatusfamiliacat,
    sistemaclasificacionfamiliacatvalido = sistemaclasificacionfamiliacat,
    subfamiliacatvalido = subfamiliacat,
    sistemaclasificacionsubfamiliacatvalido = sistemaclasificacionsubfamiliacat,
    estatussubfamiliacatvalido = estatussubfamiliacat,
    tribucatvalido = tribucat,
    sistemaclasificaciontribucatvalido = sistemaclasificaciontribucat,
    estatustribucatvalido = estatustribucat,
    generocatvalido = generocat,
    sistemaclasificaciongenerocatvalido = sistemaclasificaciongenerocat,
    autoraniogenerocatvalido = autoraniogenerocat,
    estatusgenerocatvalido = estatusgenerocat,
    subgenerocatvalido = subgenerocat,
    sistemaclasificacionsubgenerocatvalido = sistemaclasificacionsubgenerocat,
    autoraniosubgenerocatvalido = autoraniosubgenerocat,
    estatussubgenerocatvalido = estatussubgenerocat,
    epitetoespecificocatvalido = epitetoespecificocat,
    catdiccespeciecatvalido = catdiccespeciecat,
    autoranioespeciecatvalido = autoranioespeciecat,
    estatusespeciecatvalido = estatusespeciecat,
    categoriainfraespeciecatvalido = categoriainfraespeciecat,
    epitetoinfraespecificocatvalido = epitetoinfraespecificocat,
    catdiccinfraespeciecatvalido = catdiccinfraespeciecat,
    autoranioinfraespeciecatvalido = autoranioinfraespeciecat,
    estatusinfraespeciecatvalido = estatusinfraespeciecat,
	categoriainfraespecie2catvalido=categoriainfraespecie2cat,
    epitetoinfraespecifico2catvalido=epitetoinfraespecifico2cat,
    autoranioinfraespecie2catvalido=autoranioinfraespecie2cat,
    estatusinfraespecie2catvalido=estatusinfraespecie2cat,
    catdiccinfraespecie2catvalido=catdiccinfraespecie2cat,
    idnombrecatvalido = idnombrecat,
    cattaxcatvalido = cattaxcat,
    catalogocatvalido = catalogocat,
    comentarioscatvalido = comentarioscat,
    fuentecatvalido = fuentecat,
    homonimosfamiliacatvalido = homonimosfamilia,
    homonimosgenerocatvalido = homonimosgenero,
    homonimosespeciecatvalido = homonimosespecie,
    homonimosinfraespeciecatvalido = homonimosinfraespecie,
    categoriavalidocatscat = categoriacatscat,
    nombrevalidocatscat = nombrecatscat,
    estatusvalidocatscat = estatuscatscat,
    autoridadvalidocatscat = autoridadcatscat
WHERE (comentarioscat like "%completamente%" and estatuscatscat in ('válido', 'aceptado'))
or (comentarioscat like '%completamente con otra fuente%' and estatuscatscat = '');



-- Ultimo punto

update snibdtap.`#Actualiza_CompletamenteCOL` a inner join ValidacionesSCAT.cortevalidacion n on a.llaveagrupado=n.llaveagrupado
inner join catalogocentralizado.TransformaTablaNombreCOL tv on a.idcol_valido=tv.idnombre
set n.reinocatvalido= tv.Reino,
n.sistemaclasificacionreinocatvalido= tv.SistClasCatDiccReino,
n.divisionphylumcatvalido= tv.Divisionphylum,
n.sistemaclasificaciondivisionphylumcatvalido= tv.SistClasCatDiccDivisionphylum,
n.clasecatvalido= tv.Clase,
n.sistemaclasificacionclasecatvalido= tv.SistClasCatDiccClase,
n.ordencatvalido= tv.Orden,
n.sistemaclasificacionordencatvalido= tv.SistClasCatDiccOrden,
n.subordencatvalido= tv.Suborden,
n.sistemaclasificacionsubordencatvalido= tv.SistClasCatDiccSuborden,
n.familiacatvalido= tv.Familia,
n.sistemaclasificacionfamiliacatvalido= tv.SistClasCatDiccFamilia,
n.estatusfamiliacatvalido= tv.EstatusFamilia,
n.subfamiliacatvalido= tv.Subfamilia,
n.sistemaclasificacionsubfamiliacatvalido= tv.SistClasCatDiccSubfamilia,
n.estatussubfamiliacatvalido= tv.EstatusSubfamilia,
n.tribucatvalido= tv.Tribu,
n.sistemaclasificaciontribucatvalido= tv.SistClasCatDiccTribu,
n.estatustribucatvalido= tv.EstatusTribu,
n.generocatvalido= tv.Genero,
n.sistemaclasificaciongenerocatvalido= tv.SistClasCatDiccGenero,
n.estatusgenerocatvalido= tv.EstatusGenero,
n.autoraniogenerocatvalido= tv.AutoridadGenero,
n.subgenerocatvalido= tv.Subgenero,
n.sistemaclasificacionsubgenerocatvalido= tv.SistClasCatDiccSubgenero,
n.autoraniosubgenerocatvalido= tv.AutoridadSubgenero,
n.estatussubgenerocatvalido= tv.EstatusSubgenero,
n.epitetoespecificocatvalido= tv.Especie_epiteto,
n.catdiccespeciecatvalido= tv.SistClasCatDiccEspecie_epiteto,
n.estatusespeciecatvalido= tv.EstatusEspecie_epiteto,
n.autoranioespeciecatvalido= tv.AutoridadEspecie_epiteto,
n.categoriainfraespeciecatvalido= tv.Categinfra,
n.epitetoinfraespecificocatvalido= tv.Nombreinfra,
n.catdiccinfraespeciecatvalido= tv.SistClasCatDiccNombreinfra,
n.estatusinfraespeciecatvalido= tv.EstatusCategInfra,
n.autoranioinfraespeciecatvalido= tv.AutoridadCategInfra,
n.categoriainfraespecie2catvalido= tv.CategSubInfra,
n.epitetoinfraespecifico2catvalido= tv.NombreSubInfra,
n.catdiccinfraespecie2catvalido= tv.SistClasCatDiccNombreSubInfra,
n.estatusinfraespecie2catvalido= tv.EstatusCategSubInfra,
n.autoranioinfraespecie2catvalido= tv.AutoridadCategSubInfra,
n.idnombrecatvalido= '',
n.cattaxcatvalido= '',
n.catalogocatvalido= '',
n.comentarioscatvalido= a.comentarioscatvalido_corregido,
n.fuentecatvalido= tv.fuente,
n.gruposcat= tv.gruposcat;

-- Ahora llenamos de Reino hasta el vinculo a partir de la TTNombre
update snibdtap.`#Actualiza_CompletamenteCOL` a inner join ValidacionesSCAT.cortevalidacion n on a.llaveagrupado=n.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre tv on a.idnombrecatvalido_corregido=tv.IdCAT
set n.reinocatvalido=if(tv.Reino='',n.reinocatvalido,tv.Reino),
n.sistemaclasificacionreinocatvalido=if(tv.SistClasCatDiccReino='',n.sistemaclasificacionreinocatvalido,tv.SistClasCatDiccReino),
n.divisionphylumcatvalido=if(tv.Divisionphylum='',n.divisionphylumcatvalido,tv.Divisionphylum),
n.sistemaclasificaciondivisionphylumcatvalido=if(tv.SistClasCatDiccDivisionphylum='',n.sistemaclasificaciondivisionphylumcatvalido,tv.SistClasCatDiccDivisionphylum),
n.clasecatvalido=if(tv.Clase='',n.clasecatvalido,tv.Clase),
n.sistemaclasificacionclasecatvalido=if(tv.SistClasCatDiccClase='',n.sistemaclasificacionclasecatvalido,tv.SistClasCatDiccClase),
n.ordencatvalido=if(tv.Orden='',n.ordencatvalido,tv.Orden),
n.sistemaclasificacionordencatvalido=if(tv.SistClasCatDiccOrden='',n.sistemaclasificacionordencatvalido,tv.SistClasCatDiccOrden),
n.subordencatvalido=if(tv.Suborden='',n.subordencatvalido,tv.Suborden),
n.sistemaclasificacionsubordencatvalido=if(tv.SistClasCatDiccSuborden='',n.sistemaclasificacionsubordencatvalido,tv.SistClasCatDiccSuborden),
n.familiacatvalido=if(tv.Familia='',n.familiacatvalido,tv.Familia),
n.sistemaclasificacionfamiliacatvalido=if(tv.SistClasCatDiccFamilia='',n.sistemaclasificacionfamiliacatvalido,tv.SistClasCatDiccFamilia),
n.estatusfamiliacatvalido=if(tv.EstatusFamilia='',n.estatusfamiliacatvalido,tv.EstatusFamilia),
n.subfamiliacatvalido=if(tv.Subfamilia='',n.subfamiliacatvalido,tv.Subfamilia),
n.sistemaclasificacionsubfamiliacatvalido=if(tv.SistClasCatDiccSubfamilia='',n.sistemaclasificacionsubfamiliacatvalido,tv.SistClasCatDiccSubfamilia),
n.estatussubfamiliacatvalido=if(tv.EstatusSubfamilia='',n.estatussubfamiliacatvalido,tv.EstatusSubfamilia),
n.tribucatvalido=if(tv.Tribu='',n.tribucatvalido,tv.Tribu),
n.sistemaclasificaciontribucatvalido=if(tv.SistClasCatDiccTribu='',n.sistemaclasificaciontribucatvalido,tv.SistClasCatDiccTribu),
n.estatustribucatvalido=if(tv.EstatusTribu='',n.estatustribucatvalido,tv.EstatusTribu),
n.generocatvalido=if(tv.Genero='',n.generocatvalido,tv.Genero),
n.sistemaclasificaciongenerocatvalido=if(tv.SistClasCatDiccGenero='',n.sistemaclasificaciongenerocatvalido,tv.SistClasCatDiccGenero),
n.estatusgenerocatvalido=if(tv.EstatusGenero='',n.estatusgenerocatvalido,tv.EstatusGenero),
n.autoraniogenerocatvalido=if(tv.AutoridadGenero='',n.autoraniogenerocatvalido,tv.AutoridadGenero),
n.subgenerocatvalido=if(tv.Subgenero='',n.subgenerocatvalido,tv.Subgenero),
n.sistemaclasificacionsubgenerocatvalido=if(tv.SistClasCatDiccSubgenero='',n.sistemaclasificacionsubgenerocatvalido,tv.SistClasCatDiccSubgenero),
n.autoraniosubgenerocatvalido=if(tv.AutoridadSubgenero='',n.autoraniosubgenerocatvalido,tv.AutoridadSubgenero),
n.estatussubgenerocatvalido=if(tv.EstatusSubgenero='',n.estatussubgenerocatvalido,tv.EstatusSubgenero),
n.epitetoespecificocatvalido=if(tv.Especie_epiteto='',n.epitetoespecificocatvalido,tv.Especie_epiteto),
n.catdiccespeciecatvalido=if(tv.SistClasCatDiccEspecie_epiteto='',n.catdiccespeciecatvalido,tv.SistClasCatDiccEspecie_epiteto),
n.estatusespeciecatvalido=if(tv.EstatusEspecie_epiteto='',n.estatusespeciecatvalido,tv.EstatusEspecie_epiteto),
n.autoranioespeciecatvalido=if(tv.AutoridadEspecie_epiteto='',n.autoranioespeciecatvalido,tv.AutoridadEspecie_epiteto),
n.categoriainfraespeciecatvalido=if(tv.Categinfra='',n.categoriainfraespeciecatvalido,tv.Categinfra),
n.epitetoinfraespecificocatvalido=if(tv.Nombreinfra='',n.epitetoinfraespecificocatvalido,tv.Nombreinfra),
n.catdiccinfraespeciecatvalido=if(tv.SistClasCatDiccNombreinfra='',n.catdiccinfraespeciecatvalido,tv.SistClasCatDiccNombreinfra),
n.estatusinfraespeciecatvalido=if(tv.EstatusCategInfra='',n.estatusinfraespeciecatvalido,tv.EstatusCategInfra),
n.autoranioinfraespeciecatvalido=if(tv.AutoridadCategInfra='',n.autoranioinfraespeciecatvalido,tv.AutoridadCategInfra),
n.categoriainfraespecie2catvalido=if(tv.CategSubInfra='',n.categoriainfraespecie2catvalido,tv.CategSubInfra),
n.epitetoinfraespecifico2catvalido=if(tv.NombreSubInfra='',n.epitetoinfraespecifico2catvalido,tv.NombreSubInfra),
n.catdiccinfraespecie2catvalido=if(tv.SistClasCatDiccNombreSubInfra='',n.catdiccinfraespecie2catvalido,tv.SistClasCatDiccNombreSubInfra),
n.estatusinfraespecie2catvalido=if(tv.EstatusCategSubInfra='',n.estatusinfraespecie2catvalido,tv.EstatusCategSubInfra),
n.autoranioinfraespecie2catvalido=if(tv.AutoridadCategSubInfra='',n.autoranioinfraespecie2catvalido,tv.AutoridadCategSubInfra),
n.idnombrecatvalido=tv.IdCAT,
n.cattaxcatvalido=tv.UltimaCategoriaTaxonomica,
n.catalogocatvalido=tv.Fuente;


update snibdtap.`#Actualiza_CompletamenteCOL` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.subordencatvalido=t.Suborden,
c.sistemaclasificacionsubordencatvalido=t.SistClasCatDiccSuborden
where t.ultimacategoriataxonomica in ('familia');

update snibdtap.`#Actualiza_CompletamenteCOL` a inner join ValidacionesSCAT.cortevalidacion c on a.llaveagrupado=c.llaveagrupado
inner join catalogocentralizado._TransformaTablaNombre t on a.idnombrecatvalido_corregido=t.idcat
set c.subordencatvalido=t.Suborden,
c.sistemaclasificacionsubordencatvalido=t.SistClasCatDiccSuborden,
c.subfamiliacatvalido=t.Subfamilia,
c.sistemaclasificacionsubfamiliacatvalido=t.SistClasCatDiccSubfamilia,
c.estatussubfamiliacatvalido=t.EstatusSubfamilia,
c.tribucatvalido=t.Tribu,
c.sistemaclasificaciontribucatvalido=t.SistClasCatDiccTribu,
c.estatustribucatvalido=t.EstatusTribu
where t.ultimacategoriataxonomica in ('género');